# Generated by Django 3.0.5 on 2020-04-18 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
            ],
        ),
    ]
